name: Format Linting Typecheck and Unit Test

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  FORCE_COLOR: 3
  TURBO_TEAM: ${{ vars.TURBO_TEAM }} # Set Turbo team (if using Turbo Remote Caching)
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }} # Set Turbo token (if using Turbo Remote Caching)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./tooling/github/setup
      - name: Lint
        run: pnpm lint && pnpm lint:ws

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./tooling/github/setup
      - name: Format
        run: pnpm format

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./tooling/github/setup
      - name: Typecheck
        run: pnpm typecheck

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install
      - name: Run Tests
        run: pnpm turbo test

  trigger-workflows:
    needs: [lint, format, typecheck, unit-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get all test, doc and src files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v44
        with:
          files_yaml: |
            nextjs: 
              - apps/nextjs/**
              - packages/**
              - .github/workflows/build-push-nextjs.yml
            expo:
              - apps/expo/**
              - packages/**
              - .github/workflows/maestro.yml
            lambda:
              - apps/lambda/**
              - packages/db
              - .github/workflows/build-push-lambda.yml

      - name: Trigger NextJS Build and Push Workflow
        if: steps.changed-files-yaml.outputs.nextjs_any_changed == 'true'
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.API_GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dobzacode/planty-turbo/actions/workflows/build-push-nextjs.yml/dispatches \
            -d '{"ref":"main"}'

      - name: Trigger Maestro e2e Testing
        if: steps.changed-files-yaml.outputs.lambda_any_changed == 'true'
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.API_GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dobzacode/planty-turbo/actions/workflows/maestro.yml/dispatches \
            -d '{"ref":"main"}'

      - name: Trigger Maestro e2e Testing
        if: steps.changed-files-yaml.outputs.expo_any_changed == 'true'
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.API_GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dobzacode/planty-turbo/actions/workflows/build-push-lambda.yml/dispatches \
            -d '{"ref":"main"}'
