name: Format Linting Typecheck and Unit Test

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  FORCE_COLOR: 3
  TURBO_TEAM: ${{ vars.TURBO_TEAM }} # Set Turbo team (if using Turbo Remote Caching)
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }} # Set Turbo token (if using Turbo Remote Caching)

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./tooling/github/setup
      - name: Lint
        run: pnpm lint && pnpm lint:ws

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./tooling/github/setup
      - name: Format
        run: pnpm format

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./tooling/github/setup
      - name: Typecheck
        run: pnpm typecheck

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install
      - name: Run Tests
        run: pnpm turbo test
