name: E2E Tests Android (Maestro + Github Action)

on: workflow_dispatch

jobs:
  generate-test-apk:
    defaults:
      run:
        working-directory: ./apps/expo
    name: Generate and Test Test APK (Maestro Cloud)
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install
      - name: 📦 Set Up JDK + Generate Test APK
        uses: ./.github/actions/setup-jdk-generate-apk
        with:
          APP_ENV: staging
          EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          GOOGLE_BASE64: ${{ secrets.GOOGLE_BASE64 }}

      - name: Upload Test APK
        uses: actions/upload-artifact@v4
        with:
          name: test-apk
          path: ./apps/expo/android/app/build/outputs/apk/release/app-release.apk

      - name: 📱 Run E2E Tests with Maestro Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v1.8.1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: ./apps/expo/android/app/build/outputs/apk/release/app-release.apk
          workspace: ./apps/expo/.maestro
          env: |
            MAESTRO_PASSWORD=${{ secrets.MAESTRO_PASSWORD }}
            MAESTRO_EMAIL=${{ secrets.MAESTRO_EMAIL }}
            APP_ID=com.corentinkittel.arozvit

  trigger-workflow:
    needs: [generate-test-apk]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger EAS build
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.API_GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/dobzacode/arozvit/actions/workflows/eas-build.yml/dispatches \
            -d '{"ref":"main"}'
